times = ('Vasco', 'Atletico Mineiro', 'Bahia', 'Botafogo', 'Paranaense', 'Chapecoense', 'Remo', 'Corinthians', 'Coritiba', 'Cruzeiro', 'Vitória', 'Flamengo', 'Fluminense', 'Gremio', 'Internacional', 'Mirassol', 'Palmeiras', 'Red Bull', 'Santos', 'São Paulo')
negocio = ('-=' * 10)
print(negocio)
print(f'Lista de times do Brasileirão: {times}')
print(negocio)
print(f'Os 5 primeiros colocados são {times[0:5]}')
print(negocio)
print(f'Os últimos 4 colocados são: {times[-4:]}')
print(negocio)
print(f'Os times em ordem alfabética: {sorted(times)}')
print(negocio)
print(f'A chapecoence ta na posição {(times.index('Chapecoense') + 1)}°')